[[Authentication.Jwt.Clients]]
ClientId = "01J2ED6BDX9J9BTYS2RVW83ME7"
RedirectUri = ["http://localhost:3000/auth/callback"]

[[Authentication.Jwt.Clients]]
ClientId = "01K7XDHJGMYQWZ029T85BGDZ28"
RedirectUri = ["https://localhost:5001/scalar/v1"]

[[Authentication.Jwt.Clients]]
ClientId = "01K7X723S04R1F5P2P8NJV5QT5"
ClientSecret = "urn:vatprc:client_secret:01K7X71YQQXWSDT2XK1ZNYMS2J"
RedirectUri = []

[Authentication.Vatsim]
Endpoint = "https://auth-dev.vatsim.net"
ClientId = "841"
ClientSecret = "SUA4O6tE0AzNjZ7Y5WSwGJSHX7vW5s6LvsGxdvsN"
RedirectUri = "https://localhost:5001/auth/callback/vatsim"
