AllowedHosts = "*"

[Serilog]
Using = [
  "Serilog.Sinks.Console",
  "Net.Vatprc.Uniapi",
  "Sentry.Serilog",
  "Serilog.Sinks.OpenTelemetry",
]

[Serilog.MinimumLevel]
Default = "Information"
[Serilog.MinimumLevel.Override]
Microsoft = "Information"
"Microsoft.AspNetCore" = "Warning"
"Microsoft.EntityFrameworkCore.Database.Command" = "Warning"
"AspNetCore.SpaYarp" = "Information"
"Yarp.ReverseProxy" = "Warning"

[Serilog.WriteTo.Console]
Name = "Console"
[Serilog.WriteTo.Console.Args]
outputTemplate = "[{Timestamp:HH:mm:ss} {Level:u3}] {Message} (at {SourceContext}) {TraceId}{NewLine}{Exception}"

[Serilog.Properties]
Application = "VATPRC-UniAPI"

[Sentry]
Dsn = ""

[ConnectionStrings]
VATPRCContext = "Host=localhost;Database=uniapi;Include Error Detail=true"

[Authentication.Jwt]
# Generate ECC key with https://dinochiesa.github.io/jwt/
PrivateKey = """
-----BEGIN PRIVATE KEY-----
......
-----END PRIVATE KEY-----
"""
PublicKey = """
-----BEGIN PUBLIC KEY-----
......
-----END PUBLIC KEY-----
"""
Issuer = "https://uniapi.vatprc.net"
AudienceFirstParty = "https://uniapi.vatprc.net"
FirstPartyExpires = 01:00:00
RefreshExpiresDays = 7
DeviceAuthzExpires = 3600

[Authentication.Vatsim]
Endpoint = "https://auth.vatsim.net"
ClientId = ""
ClientSecret = ""
RedirectUri = "https://example.com/auth/callback/vatsim"

[Authentication.Internal.VatprcAtcService]
Endpoint = "https://atcapi.vatprc.net"
TokenAudience = "https://atcapi.vatprc.net"
# Generate ECC key with https://dinochiesa.github.io/jwt/
PrivateKey = """
-----BEGIN PRIVATE KEY-----
......
-----END PRIVATE KEY-----
"""
PublicKey = """
-----BEGIN PUBLIC KEY-----
......
-----END PUBLIC KEY-----
"""

[Discourse]
Endpoint = "https://community.vatprc.net"

[Worker.Flight]
Enabled = false
PeriodInSeconds = 15
TimeoutInMinutes = 5
