name: .NET

on:
  push:
    branches: [main]
jobs:
  dotnet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.x"
          cache: true
      - run: dotnet restore --locked-mode
      - name: Build project
        run: dotnet build
      - name: Run tests
        run: dotnet test
