/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/atc/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_applications"];
        put?: never;
        post: operations["create_application"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/applications/review-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_review_sheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/applications/sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_application_sheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_application"];
        put: operations["update_application"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/applications/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["review_application"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_bookings"];
        put?: never;
        post: operations["create_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/bookings/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_my_bookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_booking"];
        put: operations["update_booking"];
        post?: never;
        delete: operations["delete_booking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/controllers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_controllers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/trainings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_training"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/trainings/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_active"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/trainings/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_training_applications"];
        put?: never;
        post: operations["create_training_application"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/trainings/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_training_application"];
        put: operations["update_training_application"];
        post?: never;
        delete: operations["delete_application"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/trainings/applications/{id}/response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["respond_to_application"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/trainings/applications/{id}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_responses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/trainings/by-user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_by_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/trainings/finished": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_finished"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/trainings/record-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_record_sheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/trainings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_training"];
        put: operations["update_training"];
        post?: never;
        delete: operations["delete_training"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atc/trainings/{id}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["set_record_sheet"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compat/euroscope/metar/metar.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_metar_by_query"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compat/euroscope/metar/{icao}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_metar_by_path"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compat/homepage/events/vatsim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["vatsim_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compat/online-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["online_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compat/trackaudio/mandatory_version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trackaudio_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compat/vplaaf/areas.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["vplaaf_areas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_events"];
        put?: never;
        post: operations["create_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/past": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_past_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/airspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_airspaces"];
        put?: never;
        post: operations["create_airspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/airspaces/{airspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_airspace"];
        post?: never;
        delete: operations["delete_airspace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/controllers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_positions"];
        put?: never;
        post: operations["create_position"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/controllers/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_position"];
        post?: never;
        delete: operations["delete_position"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/controllers/{position_id}/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["book_position"];
        post?: never;
        delete: operations["cancel_position_booking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_slots"];
        put?: never;
        post: operations["create_slot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/slots/{slot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_slot"];
        post?: never;
        delete: operations["delete_slot"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/slots/{slot_id}/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_event_slot_booking"];
        put: operations["put_booking"];
        post?: never;
        delete: operations["delete_event_slot_booking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_event"];
        put?: never;
        post: operations["update_event"];
        delete: operations["delete_event"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flights/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["active_flights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flights/by-callsign/{callsign}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["flight_by_callsign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flights/by-callsign/{callsign}/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["route_by_callsign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flights/by-callsign/{callsign}/warnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["warnings_by_callsign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flights/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["my_flight"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flights/temporary/by-plan/warnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["temporary_warnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/navdata/preferred-routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_preferred_routes"];
        put?: never;
        post: operations["create_preferred_route"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/navdata/preferred-routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_preferred_route"];
        put: operations["update_preferred_route"];
        post?: never;
        delete: operations["delete_preferred_route"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_notams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sectors/current/permission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["current_permission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_current"];
        put?: never;
        post?: never;
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/by-cid/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_user_by_cid"];
        put?: never;
        post: operations["assume_by_cid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/atc/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_my_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/atc/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_status"];
        put: operations["set_status"];
        post?: never;
        delete: operations["delete_status"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["set_roles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/__unsafe_assume_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unsafe_assume_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/device_authorization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["device_authorization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        AccessTokenRequest: {
            client_id?: string;
            client_secret?: string;
            code?: string;
            code_verifier?: string;
            device_code?: string;
            grant_type?: string;
            refresh_token?: string;
        };
        AtcApplicationDto: {
            application_filing_answers: components["schemas"]["SheetFieldAnswerDto"][];
            /** Format: date-time */
            applied_at: string;
            id: string;
            review_filing_answers?: components["schemas"]["SheetFieldAnswerDto"][] | null;
            status: components["schemas"]["AtcApplicationStatus"];
            user: components["schemas"]["UserDto"];
            user_id: string;
        };
        /** @enum {string} */
        AtcApplicationStatus: "submitted" | "in-waitlist" | "approved" | "rejected" | "aborted";
        AtcApplicationSummaryDto: {
            /** Format: date-time */
            applied_at: string;
            id: string;
            status: components["schemas"]["AtcApplicationStatus"];
            user: components["schemas"]["UserDto"];
            user_id: string;
        };
        AtcBookingDto: {
            /** Format: date-time */
            booked_at: string;
            callsign: string;
            /** Format: date-time */
            end_time: string;
            id: string;
            /** Format: date-time */
            start_time: string;
            user: components["schemas"]["UserDto"];
        };
        AtcPermissionDto: {
            position_kind_id: string;
            /** Format: date-time */
            solo_expires_at?: string | null;
            state: components["schemas"]["UserControllerState"];
        };
        AtcPermissionRequest: {
            position_kind_id: string;
            /** Format: date-time */
            solo_expires_at?: string | null;
            state: components["schemas"]["UserControllerState"];
        };
        AtcStatusDto: {
            is_absent: boolean;
            is_visiting: boolean;
            permissions: components["schemas"]["AtcPermissionDto"][];
            rating: string;
            user: components["schemas"]["UserDto"];
            user_id: string;
        };
        AtcStatusRequest: {
            is_absent: boolean;
            is_visiting: boolean;
            permissions: components["schemas"]["AtcPermissionRequest"][];
            rating: string;
        };
        CompatControllerDto: {
            callsign: string;
            /** Format: int32 */
            cid: number;
            frequency: string;
            name: string;
        };
        CompatFutureControllerDto: {
            callsign: string;
            end: string;
            /** Format: date-time */
            end_utc: string;
            name: string;
            start: string;
            /** Format: date-time */
            start_utc: string;
        };
        CompatPilotDto: {
            aircraft?: string | null;
            arrival?: string | null;
            callsign: string;
            /** Format: int32 */
            cid: number;
            departure?: string | null;
            name: string;
        };
        CompatVatprcStatusDto: {
            controllers: components["schemas"]["CompatControllerDto"][];
            future_controllers: components["schemas"]["CompatFutureControllerDto"][];
            /** Format: date-time */
            last_updated: string;
            pilots: components["schemas"]["CompatPilotDto"][];
        };
        DeviceAuthorizationRequest: {
            client_id: string;
            scope?: string | null;
        };
        DeviceAuthorizationResponse: {
            device_code: string;
            /** Format: int32 */
            expires_in: number;
            /** Format: int32 */
            interval?: number | null;
            user_code: string;
            verification_uri: string;
            verification_uri_complete?: string | null;
        };
        EventAirspaceDto: {
            /** Format: date-time */
            created_at: string;
            description: string;
            event_id: string;
            icao_codes: string[];
            id: string;
            name: string;
            /** Format: date-time */
            updated_at: string;
        };
        EventAtcPositionBookingDto: {
            /** Format: date-time */
            booked_at: string;
            user: components["schemas"]["UserDto"];
            user_id: string;
        };
        EventAtcPositionDto: {
            booking?: null | components["schemas"]["EventAtcPositionBookingDto"];
            callsign: string;
            /** Format: date-time */
            end_at: string;
            event: components["schemas"]["EventDto"];
            id: string;
            minimum_controller_state: components["schemas"]["UserControllerState"];
            position_kind_id: string;
            remarks?: string | null;
            /** Format: date-time */
            start_at: string;
        };
        EventBookingDto: {
            /** Format: date-time */
            created_at: string;
            id: string;
            /** Format: date-time */
            updated_at: string;
            user?: null | components["schemas"]["UserDto"];
            user_id: string;
        };
        EventDto: {
            community_link?: string | null;
            /** Format: date-time */
            created_at: string;
            description: string;
            /** Format: date-time */
            end_at: string;
            /** Format: date-time */
            end_booking_at?: string | null;
            id: string;
            image_url?: string | null;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            start_atc_booking_at?: string | null;
            /** Format: date-time */
            start_booking_at?: string | null;
            title: string;
            title_en?: string | null;
            /** Format: date-time */
            updated_at: string;
            vatsim_link?: string | null;
        };
        EventSaveRequest: {
            community_link?: string | null;
            description: string;
            /** Format: date-time */
            end_at: string;
            /** Format: date-time */
            end_booking_at?: string | null;
            image_url?: string | null;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            start_atc_booking_at?: string | null;
            /** Format: date-time */
            start_booking_at?: string | null;
            title: string;
            title_en?: string | null;
            vatsim_link?: string | null;
        };
        EventSlotDto: {
            aircraft_type_icao?: string | null;
            airspace: components["schemas"]["EventAirspaceDto"];
            airspace_id: string;
            booking?: null | components["schemas"]["EventBookingDto"];
            callsign?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            enter_at: string;
            event_id: string;
            id: string;
            /** Format: date-time */
            leave_at?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        FlightDto: {
            aircraft: string;
            /** Format: int64 */
            altitude: number;
            arrival: string;
            callsign: string;
            cid: string;
            /** Format: int64 */
            cruising_level: number;
            departure: string;
            equipment: string;
            id: string;
            /** Format: date-time */
            last_observed_at: string;
            navigation_performance: string;
            raw_route: string;
            transponder: string;
        };
        FlightFix: {
            identifier: string;
        };
        FlightLeg: {
            from: components["schemas"]["FlightFix"];
            leg_identifier: string;
            to: components["schemas"]["FlightFix"];
        };
        HealthResponse: {
            database: string;
            status: string;
        };
        /** @enum {string} */
        LevelRestrictionType: "standard-even" | "standard-odd" | "standard" | "flight-level-even" | "flight-level-odd" | "flight-level";
        NotamDto: {
            language_code: string;
            link: string;
            title: string;
        };
        PreferredRouteDto: {
            allowed_altitudes: number[];
            arrival: string;
            cruising_level_restriction: components["schemas"]["LevelRestrictionType"];
            departure: string;
            id: string;
            /** Format: int32 */
            minimal_altitude: number;
            raw_route: string;
            remarks: string;
            /** Format: date-time */
            valid_from?: string | null;
            /** Format: date-time */
            valid_until?: string | null;
        };
        PreferredRouteSaveRequest: {
            allowed_altitudes?: number[];
            arrival: string;
            cruising_level_restriction: components["schemas"]["LevelRestrictionType"];
            departure: string;
            /** Format: int32 */
            minimal_altitude: number;
            raw_route: string;
            remarks: string;
            /** Format: date-time */
            valid_from?: string | null;
            /** Format: date-time */
            valid_until?: string | null;
        };
        SectorPermissionResponse: {
            has_permission: boolean;
            sector_type: string;
        };
        SheetDto: {
            fields: components["schemas"]["SheetFieldDto"][];
            id: string;
            name: string;
        };
        SheetFieldAnswerDto: {
            answer: string;
            field: components["schemas"]["SheetFieldDto"];
        };
        SheetFieldDto: {
            description_en?: string | null;
            description_zh?: string | null;
            id: string;
            is_deleted: boolean;
            kind: string;
            name_en?: string | null;
            name_zh: string;
            /** Format: int64 */
            sequence: number;
            sheet_id: string;
            single_choice_options: string[];
        };
        TokenDto: {
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            issued_at: string;
            user: components["schemas"]["UserDto"];
        };
        TokenResponse: {
            access_token: string;
            /** Format: int32 */
            expires_in: number;
            refresh_token?: string | null;
            scope: string;
            token_type: string;
        };
        TrainingApplicationDto: {
            /** Format: date-time */
            created_at: string;
            id: string;
            name: string;
            slots: components["schemas"]["TrainingApplicationSlotDto"][];
            status: components["schemas"]["TrainingApplicationStatus"];
            train_id?: string | null;
            trainee: components["schemas"]["UserDto"];
            trainee_id: string;
            /** Format: date-time */
            updated_at: string;
        };
        TrainingApplicationResponseDto: {
            application_id: string;
            comment: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            is_accepted: boolean;
            trainer: components["schemas"]["UserDto"];
            trainer_id: string;
            /** Format: date-time */
            updated_at: string;
        };
        TrainingApplicationSlotDto: {
            application_id: string;
            /** Format: date-time */
            end_at: string;
            id: string;
            /** Format: date-time */
            start_at: string;
        };
        /** @enum {string} */
        TrainingApplicationStatus: "pending" | "accepted" | "rejected" | "cancelled";
        TrainingDto: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            end_at: string;
            id: string;
            name: string;
            record_sheet_filing?: components["schemas"]["SheetFieldAnswerDto"][] | null;
            record_sheet_filing_id?: string | null;
            /** Format: date-time */
            start_at: string;
            trainee: components["schemas"]["UserDto"];
            trainee_id: string;
            trainer: components["schemas"]["UserDto"];
            trainer_id: string;
            /** Format: date-time */
            updated_at: string;
        };
        UnsafeAssumeUserRequest: {
            cid: string;
            email?: string | null;
            full_name?: string | null;
            id?: string | null;
            roles?: string[] | null;
        };
        UploadImageResponse: {
            url: string;
        };
        /** @enum {string} */
        UserControllerState: "student" | "under-mentor" | "solo" | "certified" | "mentor";
        UserDto: {
            cid: string;
            /** Format: date-time */
            created_at: string;
            direct_roles: string[];
            full_name: string;
            id: string;
            moodle_account?: null | components["schemas"]["UserMoodleInfoDto"];
            roles: string[];
            /** Format: date-time */
            updated_at: string;
        };
        UserMoodleInfoDto: {
            id: string;
        };
        WarningMessage: {
            field: components["schemas"]["WarningMessageField"];
            field_index?: number | null;
            message_code: components["schemas"]["WarningMessageCode"];
            parameter?: string | null;
        };
        /** @enum {string} */
        WarningMessageCode: "no-rvsm" | "no-rnav1" | "rnp-ar" | "rnp-ar-without-rf" | "no-transponder" | "route-direct-segment" | "route-leg-direction" | "airway-require-approval" | "not-preferred-route" | "cruising-level-mismatch" | "cruising-level-not-allowed" | "route-match-preferred";
        /** @enum {string} */
        WarningMessageField: "equipment" | "transponder" | "navigation-performance" | "route" | "cruising-level";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    list_applications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcApplicationSummaryDto"][];
                };
            };
        };
    };
    create_application: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcApplicationSummaryDto"];
                };
            };
        };
    };
    get_review_sheet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetDto"];
                };
            };
        };
    };
    get_application_sheet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetDto"];
                };
            };
        };
    };
    get_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcApplicationDto"];
                };
            };
        };
    };
    update_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcApplicationDto"];
                };
            };
        };
    };
    review_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcApplicationDto"];
                };
            };
        };
    };
    list_bookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcBookingDto"][];
                };
            };
        };
    };
    create_booking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcBookingDto"];
                };
            };
        };
    };
    list_my_bookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcBookingDto"][];
                };
            };
        };
    };
    get_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcBookingDto"];
                };
            };
        };
    };
    update_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcBookingDto"];
                };
            };
        };
    };
    delete_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcBookingDto"];
                };
            };
        };
    };
    list_controllers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcStatusDto"][];
                };
            };
        };
    };
    create_training: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDto"];
                };
            };
        };
    };
    list_active: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDto"][];
                };
            };
        };
    };
    list_training_applications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingApplicationDto"][];
                };
            };
        };
    };
    create_training_application: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingApplicationDto"];
                };
            };
        };
    };
    get_training_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training application ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingApplicationDto"];
                };
            };
        };
    };
    update_training_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training application ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingApplicationDto"];
                };
            };
        };
    };
    delete_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training application ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingApplicationDto"];
                };
            };
        };
    };
    respond_to_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training application ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingApplicationResponseDto"];
                };
            };
        };
    };
    list_responses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training application ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingApplicationResponseDto"][];
                };
            };
        };
    };
    list_by_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ULID */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDto"][];
                };
            };
        };
    };
    list_finished: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDto"][];
                };
            };
        };
    };
    get_record_sheet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetDto"];
                };
            };
        };
    };
    get_training: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDto"];
                };
            };
        };
    };
    update_training: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDto"];
                };
            };
        };
    };
    delete_training: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_record_sheet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingDto"];
                };
            };
        };
    };
    get_metar_by_query: {
        parameters: {
            query?: {
                /** @description ICAO code */
                icao?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_metar_by_path: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ICAO code */
                icao: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    vatsim_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    online_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatVatprcStatusDto"];
                };
            };
        };
    };
    trackaudio_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    vplaaf_areas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"][];
                };
            };
        };
    };
    create_event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventSaveRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"];
                };
            };
        };
    };
    list_past_events: {
        parameters: {
            query?: {
                /** @description Latest event start time to include */
                until?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"][];
                };
            };
        };
    };
    list_airspaces: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAirspaceDto"][];
                };
            };
        };
    };
    create_airspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAirspaceDto"];
                };
            };
        };
    };
    update_airspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
                /** @description Airspace ULID */
                airspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAirspaceDto"];
                };
            };
        };
    };
    delete_airspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
                /** @description Airspace ULID */
                airspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_positions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAtcPositionDto"][];
                };
            };
        };
    };
    create_position: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAtcPositionDto"];
                };
            };
        };
    };
    update_position: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
                /** @description Position ULID */
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAtcPositionDto"];
                };
            };
        };
    };
    delete_position: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
                /** @description Position ULID */
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    book_position: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
                /** @description Position ULID */
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAtcPositionBookingDto"];
                };
            };
        };
    };
    cancel_position_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
                /** @description Position ULID */
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAtcPositionBookingDto"];
                };
            };
        };
    };
    list_slots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSlotDto"][];
                };
            };
        };
    };
    create_slot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSlotDto"];
                };
            };
        };
    };
    update_slot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
                /** @description Slot ULID */
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSlotDto"];
                };
            };
        };
    };
    delete_slot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
                /** @description Slot ULID */
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_event_slot_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
                /** @description Slot ULID */
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventBookingDto"];
                };
            };
        };
    };
    put_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
                /** @description Slot ULID */
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventBookingDto"];
                };
            };
        };
    };
    delete_event_slot_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                event_id: string;
                /** @description Slot ULID */
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventBookingDto"];
                };
            };
        };
    };
    get_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"];
                };
            };
        };
    };
    update_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventSaveRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"];
                };
            };
        };
    };
    delete_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"];
                };
            };
        };
    };
    active_flights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightDto"][];
                };
            };
        };
    };
    flight_by_callsign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Callsign */
                callsign: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightDto"];
                };
            };
        };
    };
    route_by_callsign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Callsign */
                callsign: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightLeg"][];
                };
            };
        };
    };
    warnings_by_callsign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Callsign */
                callsign: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarningMessage"][];
                };
            };
        };
    };
    my_flight: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightDto"];
                };
            };
        };
    };
    temporary_warnings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarningMessage"][];
                };
            };
        };
    };
    list_preferred_routes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferredRouteDto"][];
                };
            };
        };
    };
    create_preferred_route: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferredRouteSaveRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferredRouteDto"];
                };
            };
        };
    };
    get_preferred_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Preferred route ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferredRouteDto"];
                };
            };
        };
    };
    update_preferred_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Preferred route ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferredRouteSaveRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferredRouteDto"];
                };
            };
        };
    };
    delete_preferred_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Preferred route ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferredRouteDto"];
                };
            };
        };
    };
    list_notams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotamDto"][];
                };
            };
        };
    };
    current_permission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorPermissionResponse"];
                };
            };
        };
    };
    get_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenDto"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_image: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": string;
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadImageResponse"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"][];
                };
            };
        };
    };
    get_user_by_cid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description VATSIM CID */
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    assume_by_cid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description VATSIM CID */
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    get_my_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcStatusDto"];
                };
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    get_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcStatusDto"];
                };
            };
        };
    };
    set_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtcStatusRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtcStatusDto"];
                };
            };
        };
    };
    delete_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_roles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ULID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    unsafe_assume_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnsafeAssumeUserRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    authorize: {
        parameters: {
            query: {
                /** @description OAuth response type. Must be code. */
                response_type: string;
                /** @description OAuth client identifier */
                client_id: string;
                /** @description Client redirect URI */
                redirect_uri: string;
                /** @description Opaque client state */
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to authorization destination */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    device_authorization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["DeviceAuthorizationRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceAuthorizationResponse"];
                };
            };
        };
    };
    token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AccessTokenRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
